# Generated by Django 5.1.1 on 2024-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('fr', 'French'), ('gr', 'Germanian'), ('it', 'Italian'), ('sp', 'Spanish'), ('gr', 'Greek'), ('sw', 'Sweden'), ('ar', 'Arabian')], help_text='Choose language the book is written', max_length=2),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('fr', 'French'), ('gr', 'Germanian'), ('it', 'Italian'), ('sp', 'Spanish'), ('gr', 'Greek'), ('sw', 'Sweden'), ('ar', 'Arabian')], help_text='Choose language the book is written', max_length=2),
        ),
    ]
